(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SM_Plus_Scalars",
  Authors -> "C. Duhr",
  Institutions -> "Universite catholique de Louvain (CP3).",
  Emails -> "claude.duhr@uclouvain.be",
  Date -> "14. 06. 2009",
  Version -> "1.0",
  URLs -> "http://feynrules.phys.ucl.ac.be/view/Main/StandardModelScalars",
  References -> "\"The minimal non-minimal Standard Model\", J.J. van der Bij, Phys.Lett.B636:56-59,2006, hep-ph/0603082"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[SGen] ] = Range[ 4 ]

(*     Declared particles    *)

M$ClassesDescription = {
S[4] == {
    ClassMembers :> Table[Symbol[StringJoin["S", ToString[k]]], {k, Nf}],
    SelfConjugate -> True,
    Indices -> {Index[SGen]},
    PropagatorLabel -> Sk,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MSk }
}


(*        Definitions       *)


MSk[ ___ ] := MSk;


TheLabel[ S[4, {1}] ] := "S1"
TheLabel[ S[4, {2}] ] := "S2"
TheLabel[ S[4, {3}] ] := "S3"
TheLabel[ S[4, {4}] ] := "S4"


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[4, {e1x1}] , S[4, {e2x1}] , S[4, {e3x1}] , S[4, {e4x1}] ] == {{(-I/4)*lS*(IndexDelta[e1x1, e4x1]*IndexDelta[e2x1, e3x1] + IndexDelta[e1x1, e3x1]*IndexDelta[e2x1, e4x1] + IndexDelta[e1x1, e2x1]*IndexDelta[e3x1, e4x1]), 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
};

